[package]
name = "hash_functions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
fxhash = "0.2.1"
ahash = "0.8.6"
wyhash2 = "0.2.1"
md5 = "0.7.0"

[profile.dev]
opt-level = 3